---
title: '01 - Jupyter and Stata'
author: Marina Adshade, Paul Corcuera, Giulia Lo Forte, Jane Platt
date: 2024-05-29
description: This notebook explains how to set up Jupyter, add a Stata Kernel, and connect to COMET. It is the first step to take when embarking on a research project.
categories: [econ 490, stata, setting up, intro]
format: 
  html: default
  ipynb:
      syntax-definitions: 
      - stata.xml
      kernelspec: 
        display_name: Stata
        language: Stata
        name: stata
---

## Prerequisites 

1. Have installed Stata onto your personal computer.
2. Have installed Anaconda Navigator onto your personal computer.

## Learning Outcomes

1. Connect Stata on your personal computer to Jupyter Notebook.

## 1.1 Jupyter and Stata

Before we begin, we will need to have installed Stata from the [UBC portal](https://ubc.onthehub.com/WebStore/Welcome.aspx). Please be certain to sign in using your CWL before searching for Stata. This software is free for all students in the UBC Faculty of Arts. 

We will also need to install [Anaconda Navigator](https://www.anaconda.com/) in order to be able to run our files in a local version of Jupyter Notebook.

Conda is an open-source package and environment management system. With Conda, we can create a particular directory folder (also known as environment) that will contain the packages that allow us to run Jupyter online notebooks. These notebooks run code coming from different softwares (henceforth referred as kernels): Stata, R, Python, etc. The bare minimum for our environments is some version of Python. 

The only way to set up an environment based on Stata requires us to manually connect our computer's Stata program to Jupyter Notebook.

<div class="alert alert-info">

**Note:** We only have to do this once on any computer. After that we can go directly to Jupyter Notebooks for our work. </div>

## 1.2 Setting Up Our Computer 

In order to execute the following commands on our computer, we will need to access our computer's terminal window. A terminal window includes a prompt that indicates where we enter commands. The prompt we see depends on our own system, but it often includes the name of the host we are logged in to, our current working folder, our user name, and a prompt symbol.

How you access that terminal window will depend on your operating system:

#### To open the terminal in Mac, do one of the following:

1. Click the Launchpad icon in the Dock, type "terminal" in the search field, then click Terminal.
2. In the Finder, open the /Applications/Utilities folder, then double-click Terminal.

#### To open the terminal in Windows, do one of the following:

1. Click the Start button and select "All Apps". Scroll down the Start menu, right-click on the shortcut for Windows Terminal, move to the More menu, and select "Run as administrator".  
2. Click the Search icon, start typing "command prompt", and then select Open or Run as Administrator from the search results. 

Once we have the terminal open, we can run the `conda` commands that find packages to install. This is not dissimilar to downloading software from a server. We want to make sure that the computer first finds the `conda-forge` channel which contains packages. 

To do this, we should run the following commands directly in our own terminal window in Jupyter Notebooks:

```bash
  conda config --add channels conda-forge
  conda config --set channel_priority strict
```

The goal here is to create a package bundle, i.e. an environment, where we will install some version of R, Stata Kernel, and Jupyter. You can explore the things you can download to an environment from the  `conda-forge` channel by running, for example, `conda search r-base`, `conda search stata_kernel`, etc. That way, you can see all the different versions of these packages that you can download from the different channels. 

Now we are ready to create a new environment where we can install all these packages. In this particular case, we will create an environment based on Python 3.9.7. Let us create an environment called `stata_r_env` by writing:

```bash
  conda create -n stata_r_env python=3.9.7
```

If we omit the `=3.9.7` part, we will create an environment with the default Python version. 

We want anything that we install from the channel to be part of this new environment. To do so, we need to activate it by running

```bash
  conda activate stata_r_env
```

Now that our environment is activated, we can install everything we want. We begin by installing Jupyter, which will allow us to run the interactive notebooks:

```bash
  conda install jupyter
```

## 1.3 Installing Stata Kernel on an Environment

Next, we will install the Stata Kernel by running:

```bash
  conda install -c conda-forge stata_kernel
  python -m stata_kernel.install
```

Finally, to be able to run the entire ECON 490 folder, it is highly recommended to install a stable R-version. In this particular case, we will focus on R 4.1.2. We can do this by running:

```bash
  conda install -c conda-forge r-base=4.1.2  
```

## 1.4 Running the COMET Notebooks on Your Own Computer

Now that we have installed the Stata kernel and successfully connected our own version of Stata to the notebooks, we may want to run the COMET notebooks locally on our computer.

To do so, just follow some simple steps:

1. **Download the notebooks from COMET.** 
- On the top-right corner of this webpage, we can see the menu called **"LAUNCH COMET"**. Click on the down arrow to its right and then click on **"LAUNCH LOCALLY"**. 
- A zipped folder will be automatically download to our computer. Unzip it, and within it locate a folder called `econ490`. 
- This folder contains all the Jupyter Notebooks concerning the Stata modules. Move folder `econ490-stata` to where it is most convenient for you on your computer!
2. **Open the notebooks in Jupyter.** 
- Open Anaconda Navigator and locate the Jupyter notebook tile. 
- Click on the button "Launch" in the Jupyter notebook tile. A Jupyter file browser will open in a web browser tab. 
- Click on the File Browser on the left (a folder icon) and locate your `econ490-stata` folder. Now we can open any module we may want to work on!
- Be careful! Always make sure that the Stata kernel is connected and ready to run. 
  - We may check the status of our kernel by looking at the circle on the top-right of our Notebook. It should be of color white. 
  - Moving our cursor on top of it, we should see the message `Kernel status: Idle`. 
  - The first time we open a Stata notebook, it will take a couple of seconds for the Stata kernel to connect. While connecting, the circle will be gray with a tiny thunderbolt inside. 
  - We can always interrupt or reconnect the kernel by clicking on the "Kernel" menu on the top bar.

<div class="alert alert-info">

**Note:** We only have to do step 1 once on any computer. After that, we will only have to do step 2: open directly the notebooks in Jupyter. </div>

